# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170301_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='weight_choice',
            field=models.CharField(choices=[('5', '5 Kgs'), ('10', '10 Kgs'), ('15', '15 Kgs'), ('20', '20 Kgs')], max_length=10, null=True),
        ),
    ]
