# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-21 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_equipment_weight_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='weight_choice',
        ),
    ]
