# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20170301_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymconfig',
            name='weeks_inactive',
            field=models.PositiveIntegerField(default=4, help_text='Number of weeks since the last time a user logged his presence to be                                                          considered inactive', verbose_name='Reminder of inactive members'),
        ),
    ]
